### ISSUE TITLE
Bitrise-flank integration

### ISSUE THREAD

**Issue by ripunjayanoom** [moatazeldebsy/parallelize-android-UI-Tests-with-Bitrise#2]
Hello

**Comment by ripunjayanoom** [comment]
closed

**Comment by sneha-k14** [comment]
I am trying to follow the same steps for running my android app on Firebase TestLab but facing issue 
File not found: ./flank.yml
in Run Flank step. Please help in resolving this.
Thank you!!

**Comment by moatazeldebsy** [comment]
Hi @sneha-k14 there is a step in the bitrise.yml file to generate the flank.yml file because it's required 

```
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x
            cat << FLANKEOF > ./flank.yml
            gcloud:
              results-bucket: {YOUR BUCKET NAME}
              results-dir: $BITRISE_BUILD_NUMBER
              record-video: true
              timeout: 30m
              async: false
              app: $BITRISE_APK_PATH
              test: $BITRISE_TEST_APK_PATH
              use-orchestrator: false
              environment-variables:
                coverage: true
                coverageFilePath: "/sdcard/"
                clearPackageData: true
              directories-to-pull:
              - "/sdcard/"
              performance-metrics: false
              test-targets:
                - "annotation com.sample.samplecalculator.utils.RegressionTest"
              device:
              - model: "Pixel2"
                version: "28"
            flank:
              max-test-shards: 3
              num-test-runs: 1
              shard-time: 30
              smart-flank-gcs-path: "gs://{YOUR_BUCKET_NAME}/android_ta.xml"
              test-targets-always-run:
              - "annotation com.sample.samplecalculator.utils.RegressionTest"
```

**Comment by sneha-k14** [comment]
Hi @moatazeldebsy ,

Yes I am adding this code also. All the Steps you have mentioned in your Youtube video. All the scripts as it is even though I'm facing the above mentioned issue.
Only difference is for 
test-targets:

I’m mentioning my app package name.

**Comment by moatazeldebsy** [comment]
@sneha-k14 can you share with me your bitrise.yml file if applicable?

**Comment by sneha-k14** [comment]
Hi @moatazeldebsy ,
![image](https://user-images.githubusercontent.com/96745237/148982494-66db7f13-5a2c-4e57-a9a9-6ffa6cfb4a74.png)
flank.yml not found issue resolved. But now I'm facing another issue attached above.

Below mentioned is the error I'm getting
ftl.run.exception.PermissionDenied: Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
GET https://testing.googleapis.com/v1/testEnvironmentCatalog/ios?projectId=[REDACTED]
{
  "code": 403,
  "errors": [
    {
      "domain": "global",
      "message": "Not authorized for project [REDACTED]",
      "reason": "forbidden"
    }
  ],
  "message": "Not authorized for project [REDACTED]",
  "status": "PERMISSION_DENIED"
}

Please help in resolving this.

**Comment by sneha-k14** [comment]
Hi @moatazeldebsy ,

above issue got resolved after granting some accesses to my Google Service Account. But now I am facing another issue

Flank exited with status code `1`: A general failure occurred. Possible causes include: a filename that does not exist or an HTTP/network error.
Exporting artifacts
Failed to export artifacts, error: open ./results: no such file or directory
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | flank@0.1 (exit code: 1)                                      | 6.66 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/bitrise-step-flank/issues  |
| Source: https://github.com/bitrise-steplib/bitrise-step-flank                |
+---+---------------------------------------------------------------+----------+

Please guide me to resolve this.
Thank you.

**Comment by sneha-k14** [comment]
Hi @moatazeldebsy ,

above issue got resolved after granting some accesses to my Google Service Account. But now I am facing another issue

Flank exited with status code 1: A general failure occurred. Possible causes include: a filename that does not exist or an HTTP/network error.
Exporting artifacts
Failed to export artifacts, error: open ./results: no such file or directory
| |
+---+---------------------------------------------------------------+----------+
| x | flank@0.1 (exit code: 1) | 6.66 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/bitrise-step-flank/issues |
| Source: https://github.com/bitrise-steplib/bitrise-step-flank |
+---+---------------------------------------------------------------+----------+

Please guide me to resolve this.
Thank you.
